import { DeepReadonly, MapComponentDefinition } from "@dcl/sdk/ecs"
import { isServer } from "@dcl/sdk/network"

import { ComponentManager } from "src/shared/components/componentManager"
import { EntityKeyOptions, normalizeEntityKey } from "src/shared/components/types"


type ComponentListener<T> = (data: T | undefined) => void


/**
 * STABLE — thin read/write/watch helpers for registered components.
 *
 * Resolves the host entity and enforces registry write modes. Change
 * notifications use the SDK `component.onChange` API.
 *
 * Do not edit this file to add game components. Add schemas under `definitions/`
 * and register them in `registry.ts`.
 */
export namespace ComponentStore {

	const pendingMain: Array<() => void> = []


	// MARK: canWrite
	function canWrite(component: MapComponentDefinition<any>): boolean {
		const mode = ComponentManager.getRegistration(component).mode
		if (mode === 'client') return !isServer()
		return isServer()
	}


	// MARK: init
	/**
	 * Attaches any `onChange` subscriptions that waited for the main entity.
	 * Call after ComponentManager is ready.
	 */
	export function init(): void {
		const queued = pendingMain.splice(0)
		for (const attach of queued) {
			attach()
		}
	}


	// MARK: getOrNull
	/**
	 * Returns component data, or null if its entity or value is unavailable.
	 */
	export function getOrNull<T>(
		component: MapComponentDefinition<T>,
		options? : EntityKeyOptions
	): DeepReadonly<T> | null {
		const entity = ComponentManager.resolveEntity(component, options)
		if (entity === undefined) return null

		return component.getOrNull(entity)
	}


	// MARK: getMutableOrNull
	/**
	 * Returns mutable component data, or null when unavailable or this side cannot write it.
	 */
	export function getMutableOrNull<T>(
		component: MapComponentDefinition<T>,
		options? : EntityKeyOptions
	): T | null {
		if (!canWrite(component)) return null

		const entity = ComponentManager.resolveEntity(component, options)
		if (entity === undefined) return null

		return component.getMutableOrNull(entity)
	}


	// MARK: createOrReplace
	/**
	 * Creates or replaces component data. Returns null when this side cannot write it.
	 */
	export function createOrReplace<T>(
		component: MapComponentDefinition<T>,
		value    : Partial<T>,
		options? : EntityKeyOptions
	): T | null {
		if (!canWrite(component)) return null

		const entity = ComponentManager.resolveEntity(component, options)
		if (entity === undefined) return null

		return component.createOrReplace(entity, value)
	}


	// MARK: onChange
	/**
	 * Subscribes to SDK component changes on the resolved entity.
	 * Pass `{ key }` to watch one keyed instance. Returns an unsubscribe for the wait, not the SDK hook.
	 */
	export function onChange<T>(
		component: MapComponentDefinition<T>,
		listener : ComponentListener<T>,
		options? : EntityKeyOptions
	): () => void {
		let attached  = false
		let unsubWait : (() => void) | undefined

		const attach = (): boolean => {
			if (attached) return true

			const entity = ComponentManager.resolveEntity(component, options)
			if (entity === undefined) return false

			attached = true
			listener(component.getOrNull(entity) as T | undefined)
			component.onChange(entity, (current) => {
				listener(current as T | undefined)
			})
			unsubWait?.()
			unsubWait = undefined
			return true
		}

		if (attach()) {
			return () => {}
		}

		const entry = ComponentManager.getRegistration(component)
		if (entry.entityGroup === 'main') {
			pendingMain.push(attach)
			return () => {}
		}

		if (!options?.key) {
			return () => {}
		}

		const wanted = normalizeEntityKey(options.key)
		unsubWait = ComponentManager.onKeyedEntity(entry.entityGroup, (_entity, key) => {
			if (normalizeEntityKey(key) !== wanted) return
			attach()
		})

		return () => {
			unsubWait?.()
		}
	}
}
