import { engine, Entity, MapComponentDefinition } from "@dcl/sdk/ecs"
import { isServer, syncEntity } from "@dcl/sdk/network"
import { AUTH_SERVER_PEER_ID } from "@dcl/sdk/network/message-bus-sync"

import { keyedEntityGroups, MAIN_DISCOVERY_COMPONENT, MAIN_ENTITY_SYNC_ID, registry } from "src/shared/components/registry"
import { ComponentMode, ComponentRegistration, EntityGroupId, EntityKeyOptions, getGroupKeyField, normalizeEntityKey, readIdentityKey, toIdentityFieldValue } from "src/shared/components/types"


type KeyedEntityListener = (entity: Entity, key: string) => void


/**
 * STABLE — component lifecycle (create, sync, seed, entity lookup).
 *
 * Do not edit this file to add game components. Add schemas under `definitions/`
 * and register them in `registry.ts`.
 */
export namespace ComponentManager {

	// MARK: Vars
	let mainEntity   : Entity | undefined = undefined
	let isInitialised: boolean            = false

	const keyedEntities           = new Map<EntityGroupId, Map<string, Entity>>()
	const keyedEntityListeners    = new Map<EntityGroupId, Set<KeyedEntityListener>>()
	const clientReadyResolvers    : Array<() => void> = []
	const registrationByComponent = new Map<MapComponentDefinition<any>, ComponentRegistration>()


	// MARK: ensureRegistry
	function ensureRegistry(): void {
		if (registrationByComponent.size > 0) return

		for (const entry of registry) {
			registrationByComponent.set(entry.component, entry)
		}
		for (const group of keyedEntityGroups) {
			if (!keyedEntities.has(group.id)) {
				keyedEntities.set(group.id, new Map())
			}
		}
	}


	// MARK: getRegistration
	/**
	 * Returns the registry entry for a component.
	 */
	export function getRegistration(component: MapComponentDefinition<any>): ComponentRegistration {
		ensureRegistry()
		const entry = registrationByComponent.get(component)
		if (!entry) {
			throw new Error(`ComponentManager: getRegistration: component ${component.componentId} is not in registry.ts`)
		}
		return entry
	}


	// MARK: entriesFor
	function entriesFor(
		groupId: EntityGroupId,
		modes? : ComponentMode[]
	): ComponentRegistration[] {
		ensureRegistry()
		return registry.filter((entry) => {
			if (entry.entityGroup !== groupId) return false
			if (modes && !modes.includes(entry.mode)) return false
			return true
		})
	}


	// MARK: protectServerEntity
	function protectServerEntity(
		entity : Entity,
		entries: ComponentRegistration[]
	): void {
		for (const entry of entries) {
			const component = entry.component
			if (typeof component.validateBeforeChange !== 'function') continue

			component.validateBeforeChange(entity, (value) => {
				if (entry.validate && !entry.validate(value)) {
					console.log(`ComponentManager: protectServerEntity: rejected ${component.componentName} from ${value.senderAddress}`)
					return false
				}
				return value.senderAddress === AUTH_SERVER_PEER_ID
			})
		}
	}


	// MARK: seedEntries
	function seedEntries(
		entity : Entity,
		entries: ComponentRegistration[]
	): void {
		for (const entry of entries) {
			if (!entry.defaults) continue
			entry.component.createOrReplace(entity, entry.defaults())
		}
	}


	// MARK: syncAndProtect
	function syncAndProtect(
		entity : Entity,
		entries: ComponentRegistration[],
		syncId?: number
	): void {
		const synced = entries.filter((entry) => entry.mode === 'synced')
		if (synced.length === 0) return

		const componentIds = synced.map((entry) => entry.component.componentId)
		if (syncId !== undefined) {
			syncEntity(entity, componentIds, syncId)
		} else {
			syncEntity(entity, componentIds)
		}
		protectServerEntity(entity, synced)
	}


	// MARK: init
	/**
	 * Boots entities on the server, or starts client discovery.
	 */
	export function init(): void {
		if (isInitialised) {
			console.log('ComponentManager: init: already initialised, skipping')
			return
		}
		isInitialised = true
		ensureRegistry()
		isServer() ? initServer() : initClient()
	}


	// MARK: initServer
	function initServer(): void {
		console.log('ComponentManager: initServer: creating main entity')

		const entity = engine.addEntity()
		mainEntity = entity

		const mainEntries = entriesFor('main')
		seedEntries(entity, entriesFor('main', ['synced', 'server']))
		syncAndProtect(entity, mainEntries, MAIN_ENTITY_SYNC_ID)
	}


	// MARK: initClient
	function initClient(): void {
		console.log('ComponentManager: initClient: starting discovery watcher')

		const watcher = (): void => {
			for (const [entity] of engine.getEntitiesWith(MAIN_DISCOVERY_COMPONENT as any)) {
				if (mainEntity === undefined) {
					mainEntity = entity
					console.log('ComponentManager: initClient: discovered main entity')
				}
			}

			if (mainEntity === undefined) return

			engine.removeSystem(watcher)
			seedEntries(mainEntity, entriesFor('main', ['client']))

			const resolvers = clientReadyResolvers.splice(0)
			for (const resolve of resolvers) resolve()
		}

		engine.addSystem(watcher)
		engine.addSystem(discoverKeyedEntities)
	}


	// MARK: discoverKeyedEntities
	/**
	 * Registers keyed-group entities as their identity components appear on the client.
	 */
	function discoverKeyedEntities(): void {
		for (const group of keyedEntityGroups) {
			const keyField = getGroupKeyField(group)
			const map      = keyedEntities.get(group.id) ?? new Map<string, Entity>()
			keyedEntities.set(group.id, map)

			for (const [entity, identity] of engine.getEntitiesWith(group.keyComponent as any)) {
				const key = readIdentityKey(identity, keyField)
				if (!key) continue

				const normalized = normalizeEntityKey(key)
				if (map.get(normalized) === entity) continue

				map.set(normalized, entity)
				notifyKeyedEntity(group.id, entity, normalized)
			}
		}
	}


	// MARK: onClientReady
	/**
	 * Resolves when the client has discovered the main entity and seeded local components.
	 */
	export function onClientReady(): Promise<void> {
		if (isServer() || isReady()) return Promise.resolve()

		return new Promise<void>((resolve) => {
			clientReadyResolvers.push(resolve)
		})
	}


	// MARK: isReady
	/**
	 * True once the main entity exists.
	 */
	export function isReady(): boolean {
		return mainEntity !== undefined
	}


	// MARK: getMainEntity
	/**
	 * Returns the main gameplay entity. Throws if not ready.
	 */
	export function getMainEntity(): Entity {
		if (mainEntity === undefined) {
			throw new Error('ComponentManager: getMainEntity: entity not yet available')
		}
		return mainEntity
	}


	// MARK: resolveEntity
	/**
	 * Resolves the entity that hosts a registered component.
	 */
	export function resolveEntity(
		component: MapComponentDefinition<any>,
		options? : EntityKeyOptions
	): Entity | undefined {
		const entry = getRegistration(component)

		if (entry.entityGroup === 'main') {
			return mainEntity
		}

		const key = options?.key
		if (!key) {
			console.error(`ComponentManager: resolveEntity: group "${entry.entityGroup}" requires options.key`)
			return undefined
		}

		return getKeyedEntity(entry.entityGroup, key)
	}


	// MARK: getKeyedEntity
	/**
	 * Returns a keyed group entity, discovering it on the client if needed.
	 */
	export function getKeyedEntity(
		groupId: EntityGroupId,
		key    : string
	): Entity | undefined {
		ensureRegistry()

		const map        = keyedEntities.get(groupId) ?? new Map<string, Entity>()
		const normalized = normalizeEntityKey(key)
		keyedEntities.set(groupId, map)

		const groupConfig = keyedEntityGroups.find((g) => g.id === groupId)
		if (!groupConfig) return undefined

		const keyField = getGroupKeyField(groupConfig)
		const known    = map.get(normalized)
		if (known !== undefined) {
			const identity    = groupConfig.keyComponent.getOrNull(known)
			const identityKey = readIdentityKey(identity, keyField)
			if (identityKey && normalizeEntityKey(identityKey) === normalized) {
				return known
			}
			map.delete(normalized)
		}

		for (const [entity, identity] of engine.getEntitiesWith(groupConfig.keyComponent as any)) {
			const identityKey = readIdentityKey(identity, keyField)
			if (!identityKey) continue
			if (normalizeEntityKey(identityKey) !== normalized) continue

			map.set(normalized, entity)
			notifyKeyedEntity(groupId, entity, normalized)
			return entity
		}

		return undefined
	}


	// MARK: createGroupEntity
	/**
	 * Creates or updates a keyed entity (server only).
	 */
	export function createGroupEntity(
		groupId : EntityGroupId,
		key     : string,
		initial?: Record<number, unknown>
	): Entity | undefined {
		if (!isServer()) return undefined
		ensureRegistry()

		const existing = getKeyedEntity(groupId, key)
		const entity   = existing ?? engine.addEntity()
		const entries  = entriesFor(groupId)

		for (const entry of entries) {
			const fromInitial = initial?.[entry.component.componentId]
			if (fromInitial != null) {
				entry.component.createOrReplace(entity, fromInitial)
				continue
			}

			if (entry.component.getOrNull(entity) !== null) continue
			if (!entry.defaults) continue
			entry.component.createOrReplace(entity, entry.defaults())
		}

		const groupConfig = keyedEntityGroups.find((g) => g.id === groupId)
		if (groupConfig) {
			const keyField = getGroupKeyField(groupConfig)
			const prior    = groupConfig.keyComponent.getOrNull(entity) as Record<string, unknown> | null
			groupConfig.keyComponent.createOrReplace(entity, {
				...(prior ?? {}),
				[keyField]: toIdentityFieldValue(key),
			})
		}

		if (existing === undefined) {
			syncAndProtect(entity, entries)
		}

		const map        = keyedEntities.get(groupId) ?? new Map<string, Entity>()
		const normalized = normalizeEntityKey(key)
		map.set(normalized, entity)
		keyedEntities.set(groupId, map)
		notifyKeyedEntity(groupId, entity, normalized)

		return entity
	}


	// MARK: removeGroupEntity
	/**
	 * Removes a keyed group entity (server only).
	 */
	export function removeGroupEntity(
		groupId: EntityGroupId,
		key    : string
	): void {
		if (!isServer()) return

		const entity = getKeyedEntity(groupId, key)
		if (entity === undefined) return

		engine.removeEntity(entity)
		keyedEntities.get(groupId)?.delete(normalizeEntityKey(key))
	}


	// MARK: onKeyedEntity
	/**
	 * Subscribes to keyed-entity create/discover. Existing entities are replayed immediately.
	 */
	export function onKeyedEntity(
		groupId : EntityGroupId,
		listener: KeyedEntityListener
	): () => void {
		ensureRegistry()

		if (!keyedEntityListeners.has(groupId)) {
			keyedEntityListeners.set(groupId, new Set())
		}
		keyedEntityListeners.get(groupId)!.add(listener)

		const known = keyedEntities.get(groupId)
		if (known) {
			for (const [knownKey, knownEntity] of known) {
				listener(knownEntity, knownKey)
			}
		}

		return () => {
			keyedEntityListeners.get(groupId)?.delete(listener)
		}
	}


	// MARK: notifyKeyedEntity
	function notifyKeyedEntity(
		groupId: EntityGroupId,
		entity : Entity,
		key    : string
	): void {
		const listeners = keyedEntityListeners.get(groupId)
		if (!listeners) return

		for (const listener of listeners) {
			listener(entity, key)
		}
	}
}
